### ISSUE TITLE
the jScrollPane plugin appears to not work correctly when used on children of absolute positioned elements.

### ISSUE THREAD

**Issue by eblu** [vitch/jScrollPane#104]
theres just no other way of saying it. the plugin breaks down completely when applied to elements that are children of absolute positioned elements (in my case: divs)

its Always the jspPane div that winds up with the problematic behavior, and it :
1. gives itself a width of 0
2. gives itself a left margin of: 4+the width of the content it should be displaying.

this makes the content invisible. every time.

**Comment by illuusio** [comment]
Ok as this is duplicate and if this is still issue please write note
