### ISSUE TITLE
IE 9 slow script response when initializing/resizing scrolled large content

### ISSUE THREAD

**Issue by npfistnerp** [vitch/jScrollPane#111]
With some debugging I found the answer:
In jquery.jscrollpane.js, function initialiseVerticalScroll() uses a very inperformant selection (at least for IE) to resize the vertical scrollbar:

```
container.find('>.jspVerticalBar>.jspCap:visible,>.jspVerticalBar>.jspArrow').each(
```

Especially when _container_ contains a lot of elements it seems to trouble IE.

A fix is very simple, due to the fact that _.jspVerticalBar_ is already known as _verticalBar_:

```
verticalBar.find('>.jspCap:visible,>.jspArrow').each(
```

Same Problem/Solution should apply to the corresponding horizontal bar.

Hope it helps someone stumbling apon the same performance issues.

**Comment by illuusio** [comment]
If still issue please comment and I'll re-open
