### ISSUE TITLE
innerWidth bug

### ISSUE THREAD

**Issue by ghost** [vitch/jScrollPane#112]
thanks for the great plugin.

when the panewidth is calculated:

```
            originalPaddingTotalWidth = (parseInt(elem.css('paddingLeft'), 10) || 0) +
                                        (parseInt(elem.css('paddingRight'), 10) || 0);
...
                    paneWidth = elem.innerWidth() + originalPaddingTotalWidth;
...
                    elem.width(paneWidth);
```

I looked at the definition for innerWidth() at http://api.jquery.com/innerWidth/ and it seems it already includes the padding.  So the padding is being added to the width twice.

**Comment by illuusio** [comment]
This should be fixed if not then please write note
