### ISSUE TITLE
Apply Active and Hover states to .jspVerticalBar/.jspHorizontalBar containers

### ISSUE THREAD

**Issue by nelsonad** [vitch/jScrollPane#113]
Currently the .jspActive and .jspHover states are only added to the drag element, if the states were added to the bar instead or in addition to (new states .jspBarActive/.jspBarHover), this would allow for custom styling of the track bar, arrows, and drag element when active or hovered.

My scenario is that I want a tranparent trackbar unless the user is currently dragging the drag element or if the user mouses over any element in the track bar.

**Comment by illuusio** [comment]
If this is still issue please write note to reopen
