### ISSUE TITLE
pane contentHeight incorrect in specific situation with fix/solution

### ISSUE THREAD

**Issue by Basdub** [vitch/jScrollPane#115]
My situation is my element to witch I apply the jScrollPane has no text but 2 inner div with absolute position top:0 and fixed height in px.

version: jScrollPane - v2.0.0beta11 - 2011-07-04 

at line 445 we have

```
            contentHeight = pane.outerHeight();
            percentInViewV = contentHeight / paneHeight;
```

contentHeight always evaluate to zero and I assume it's because there is no sizable "text".

To solve this issue, I have added code between the 2 previous line so that it now looks like this:

```
            contentHeight = pane.outerHeight();
                            if(contentHeight == 0){
                                // try the height of children
                                $.each(pane.children(),function(i,v){
                                    if($(v).outerHeight() > contentHeight){
                                        contentHeight = $(v).height();
                                    }
                                });
                            }
            percentInViewV = contentHeight / paneHeight;
```

I think that your TODO: at line 99 would be for this kind of situation. But I think this is a good fix and it doesn't impact current behavior.

**Comment by illuusio** [comment]
If this is still issue. Please reopen
