### ISSUE TITLE
bad anchors behaviour

### ISSUE THREAD

**Issue by xnyl** [vitch/jScrollPane#121]
Hello.

When accessing anchors from other sites, many browsers seem to behave other way.

When accessing this link from other site (or reloading it) :
http://jscrollpane.kelvinluck.com/anchors.html#para2
- Chrome 16 OS X: Pane jumps out of view area + global scroll to anchor
- Chrome 15 Windows: Pane jumps out of view area,+ global scroll to anchor
- Safari 5 OS X: Pane jumps out of view area +  global scroll to anchor , same as Chrome
- Firefox 8 OS X: behaves properly!
- Opera 10 Windows: Pane jumps out of view area +  global scroll to anchor
- IE 8 Windows: nothing happens
- Firefox 3.6 Windows: behaves properly!

When clicking achors links from the same site:
Clicking anchors like href='#para2'  from all mentioned browsers is OK,
BUT:
Clicking anchors like href='/anchors.html#para2' causes wrong behaviours:
- Chrome, Safari, Firefox, IE on all OS: Pane jumps out of view area
- Opera Windows: Pane jumps out of view area + globall scroll to anchor

Have earlier version of jScrollPane had same issues?

Cheers Tom

**Comment by illuusio** [comment]
If still issue please reopen and write note.
