### ISSUE TITLE
Scrollpane loses track of contentWidth of pane, causes arrows to misbehave

### ISSUE THREAD

**Issue by troycobb** [vitch/jScrollPane#148]
After the first initialization, the contentWidth of the scrolling pane is not re-rechecked on subsequent re-initializations. 

Therefore, when content is changed in the pane, and a re-init called (as is the suggested procedure), while the control is redrawn, the contentWidth is not updated with the new scrollWidth of the pane. So, the scrollbar misbehaves thinking it has reached the end of the scrolling extent when it has not.
- Troy

**Comment by illuusio** [comment]
If this is still issue could you try vitch/jScrollPane#361
