### ISSUE TITLE
scroll pane with embedded textarea

### ISSUE THREAD

**Issue by jamiepickett** [vitch/jScrollPane#150]
I'm having an issue scrolling a textarea that is contained within a scroll pane.  If the scroll pane is at the top, I can scroll the textarea up, and when the scroll pane is at the bottom, I can scroll the textarea down.  But I cannot scroll around the text area if the scrollbar for the scroll page is anywhere else.

Here is an example: http://jsfiddle.net/FTx98/1/

**Comment by illuusio** [comment]
If this is still issue please write a note
