### ISSUE TITLE
reinitalize doesn't work

### ISSUE THREAD

**Issue by vladmedies** [vitch/jScrollPane#151]
I've created an container with both vertical and horizontal scroll bars and I'm playing with the visibility of the container (using css display: none property). When the container becomes visible I call the reinitialize method but it doesn't work.
I look into the code and the problem seems to be here

...
// If nothing changed since last check...
if (!hasContainingSpaceChanged && previousContentWidth == contentWidth && pane.outerHeight() == contentHeight) {
    elem.width(paneWidth);
    return;
}
...

I think this is very similar with https://github.com/vitch/jScrollPane/pull/130

**Comment by illuusio** [comment]
There is newer bug reports for this. Please contribute those if you still have this issue.
