### ISSUE TITLE
Dynamically adjust height (subtract extra height)

### ISSUE THREAD

**Issue by norixx** [vitch/jScrollPane#152]
Hi there.

I need some help on this 'dynamic height demo'(http://jscrollpane.kelvinluck.com/dynamic_height.html).

My example here:
http://jsfiddle.net/qGe5m/15/

This method will calculate the height of browser window and apply to div.jspContainer.
But in my case, I have some extra header above the scroll area, and the height of this extra header
should be subtracted from div.jspContainer.

So, how do i modify JS (or CSS)?

Any solution or some link to similar posts would be greatly appreciated.
Thanks for stopping by.

**Comment by illuusio** [comment]
This should be fixed. If still issue please write a note
