### ISSUE TITLE
possible issue with inline <script> tags

### ISSUE THREAD

**Issue by mblase75** [vitch/jScrollPane#156]
This isn't comprehensively tested because I'm busy with something else, but:

While trying to implement Google's reCAPTCHA technology, I was getting strange failures -- the content of the jScrollPane panel would render up until it got to the auto-generated reCAPTCHA code, and then everything vanished. Using the browser's DOM inspector revealed that the jScrollPane div contained nothing at all.

Eventually I figured out that if I manually removed the 'script' tags from the generated reCAPTCHA code, it would render inside of the jScrollPane div just fine. Apparently jScrollPane has issues with inline script tags, which aren't exactly part of the DOM.

If this can be fixed, wonderful. For now, I'm adding a line of code that circumvents jScrollPane's initializer whenever a 'recaptcha_area' div is found.

**Comment by illuusio** [comment]
If this is still issue please write a note
