### ISSUE TITLE
Bug with <li> with css attribute position:relative

### ISSUE THREAD

**Issue by omerA** [vitch/jScrollPane#158]
Hello,

I encountered a bug with jsScrollpane in my site. I've put a &lt;ul&gt; element inside the div I was defining the jsScrollpane upon. 
The scrolling worked fine on IE and FF, but not on Chrome. The bug was as follows:
When scrolling down some &lt;li&gt;s stayed in the same spot, while others did scroll down.

I checked what was the cause of that (for a long time) and I saw that my &lt;li&gt;s had position: relative. When I took that down everything worked out fine.

I can go around it with design, but the relative attribute is important for me.

Anyone else encountered this?

**Comment by illuusio** [comment]
Ok is this still issue
