### ISSUE TITLE
margin-left on .jspPane > width of container

### ISSUE THREAD

**Issue by bjudson** [vitch/jScrollPane#166]
I've using jScrollPane on a couple of projects in the past with no issue, but on a recent project I'm stumped. The script is adding a margin-left to the .jspPane div which exceeds the width of .jspContainer (by 4 pixels), pushing all content to the right of the container, and effectively hiding it.

Live page:
http://oco.saharagray.com/awards/project/samuel-v-champion-high-school/

Calling JSP with:

```
$('#display #text').jScrollPane();
```

CSS for the container:

```
.single-oco_project #display #text {
    position: absolute;
    right: 0;
    top: 0;
    width: 312px;
    height: 550px;
    padding: 0 50px 0 30px;
    background: rgba(20, 20, 20, .85);
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#90000000,endColorstr=#90000000);
    line-height: 1.7em;
}
```

jScrollPane applies these styles to the .jspPane element:

```
margin-left: 396px;
padding: 0 50px 0 30px;
top: 0;
```

**Comment by juliancoates** [comment]
I made the same mistake, without this post I'd probably have wasted hours!

**Comment by mordonez-me** [comment]
Incredible! I have spent so much time for this, valuable information!!
