### ISSUE TITLE
Scrollbar disappears on Chrome 21.0.1180.60 m

### ISSUE THREAD

**Issue by nitinmukesh** [vitch/jScrollPane#170]
Hi,

I have used jscrollpane class in my project.

I am facing an issue which seems to be specific to Chrome browser.

To replicate the issue
1. Open Chrome browser
2. Launch the following link http://jscrollpane.kelvinluck.com/basic.html
3. Press Ctrl + F (Find box)
4. Enter "sit" without quotes in search box
5. Keep pressing Enter
6. Note the Scrollbars are disappearing.
7. If you scroll through mouse the scrollbar reappears.

Please provide a fix.

Many thanks.
Nitin

**Comment by illuusio** [comment]
If still issue please reopen and post note.
