### ISSUE TITLE
Column Layout: no Scrolling on mobile devices (iphone) since adding Google Maps Api

### ISSUE THREAD

**Issue by ghost** [vitch/jScrollPane#178]
Hey Guys,

hope you can help me:
I have a 3 column layout. each column has a customized scrollbar by using jScrollpane. In column number 2 there is a customized google map. The problem is that column number 3 is not scrolling on mobile devices, because of the google-map. i tried it out by deactivating the google map: everything works fine. ya.. but i need google map on mobile device.

Detailed Info here: http://stackoverflow.com/questions/12294295/js-google-maps-api-causes-problems-with-jscrollpane-on-mobile-devices

i found this dirty solution: $('.scroll-pane').bind('jsp-scroll-y', function(){
    $('#content').css('left','-=1px').css('left','+=1px');
});

But as you can see … This is NOT really a solution.

THX for your help!

**Comment by illuusio** [comment]
if this is still issue please reopen
