### ISSUE TITLE
arrowScrollOnHover and autoReinitialise conflict

### ISSUE THREAD

**Issue by Rylab** [vitch/jScrollPane#185]
When setting both { arrowScrollOnHover: true, autoReinitialise: true } the two intervals conflict with each other like crazy, causing the scrollbar to jump around sporadically. I've tried hacking my own way through a fix, but am not exactly sure why they're conflicting so badly. It would be nice if a future update improved the behavior when both these options are used together.

**Comment by illuusio** [comment]
Next release should fix this but if you still have issues then please write a note
