### ISSUE TITLE
Disable Vertical Scrollbar

### ISSUE THREAD

**Issue by mufaddalmw** [vitch/jScrollPane#191]
Hi, First of all Thanks for slick scrollbar script. 

I'm using jscrollbar for mobile devices, please go through below url in mobile device-
http://61.246.241.36/javascript/jscrollbar_disable_issue/index.html

Here I've a requirement to show only horizontal scrollbar in each row and want to disable vertical scrollbar reason is for disable vertical scrollbar is while scrolling page in touch screen devices (eg. android, iphone mobile) it gives trouble in page scroll.

Looking forward for the best solution soon.

Thanks 
Mufaddal

**Comment by illuusio** [comment]
This is done.
