### ISSUE TITLE
Bug in calculation of content height:  jScrollPane - v2.0.0beta12 - 2012-09-27 

### ISSUE THREAD

**Issue by bribold** [vitch/jScrollPane#192]
Hi Kelvin,

I'm using JScrollPane for a small project. I found a frustrating problem in its vertical calculations when changing the content. I wasn't adding to the content - rather I was using CSS to hide and show various LI elements within a UL.

I scanned through the code and found the following problem in resizeScrollbars()

line 470:
                contentHeight = pane.outerHeight();

Obviously this seems like a contradiction!

Looking back at the code, I found the following you had set earlier.
                contentHeight = pane[0].scrollHeight;

This makes more sense, so I replaced line 470 with that line and it worked.

Obviously there are parts of the mechanism I'm not using, so I may have missed something.

BB

**Comment by illuusio** [comment]
If still issue. Please note and reopen.
