### ISSUE TITLE
jscrollpane after ajax does not work when cache is empty

### ISSUE THREAD

**Issue by pauletienney** [vitch/jScrollPane#197]
Hello,

First of all, thank you very much for creating this script. It is great.

I have a weird problem : 
- Context : i load search results in a div and then apply jscrollpane on it.
- Problem : it does not on the first visit on the page. If my browser cache is empty the scripts runs but the vertical scrollbar does not appear. If i come back on the site and do the exact same thing, it works. Then if I empty my cache again, it won't wok on first visit.

Can't find why. Do you have any idea ?

**Comment by illuusio** [comment]
If this is still issue please provide example
