### ISSUE TITLE
IE freezes for 2 minutes / contents contains flash and iframes

### ISSUE THREAD

**Issue by scato** [vitch/jScrollPane#199]
when I initialize jScrollPane (onload) IE freezes for 2 minutes
this happens only with contents that contains flash and iframes

luckily I found the problem: appendTo(elem) on line 113
I read somewhere that appendChild is very slow in IE if there are lots of images
I read somewhere that it is safer to use innerHTML

to fix, replace:

pane = $('&lt;div class="jspPane" />').css('padding', originalPadding).html(elem.children());

with:

pane = $('&lt;div class="jspPane" />').css('padding', originalPadding).html(elem.html());
elem.html('');

sadly: there is the downside to this fix that you loose all attached event listeners...

**Comment by illuusio** [comment]
If still isseue please write note and reopen.
