### ISSUE TITLE
Issue with full page horizontal scroll

### ISSUE THREAD

**Issue by povilasp** [vitch/jScrollPane#202]
We had a discussion on stack: 

http://stackoverflow.com/questions/14078587/issue-with-full-page-horizontal-scroll/14101540#14101540

**Steps to reproduce:**

go to: http://jscrollpane.kelvinluck.com/fullpage_scroll.html

step-1 make window width smaller by clicking Restore down button.
step-2 scroll to right
step-3 now, make window width bigger by clicking Maximize button

**Problem:**

"The thing here is that jScrollPane adds jspPane a left:-***px when you scroll to the right. And never undoes the damage."

**Temp fix:**
`$(window).bind('resize', function(){ $('#full-page-container .jspPane').css('left', 'auto'); });`

**Comment by illuusio** [comment]
If this is still issue please write a note
