### ISSUE TITLE
Unable to scroll the content in Windows 8 touch screen laptop

### ISSUE THREAD

**Issue by irvgk** [vitch/jScrollPane#204]
I am using jScrollPane in my website, It is working fine in normal PC browsers and iPad, Android tablets.. 

But when I open my website on windows touch screen device I am unable to scroll the page with finger like in iPad or android tablet.

I tried this demo website(http://jscrollpane.kelvinluck.com/themes/lozenge/) also, I am unable to scroll the content with finger. I have to go to scrollbar and drag it to left/right to scroll the page. Earlier with default scroll bar I am able to scroll the page with finger now I can't with jScrollPane. 

Is this a known Issue? How can I fix this?

I am able to scroll the content(demo and my site) in Chrome

It seems #6 also had same problem like this in android/iOS

**Comment by illuusio** [comment]
If this is still issue please reopen
