### ISSUE TITLE
Improper calculation of fractional margins

### ISSUE THREAD

**Issue by Deklin** [vitch/jScrollPane#206]
I've had this issue when using bootstrap.
When using bootstrap and using a contrainer-flud then a row-fluid and then a span3 and span9
the scroll area gets messed up in the span9 because bootstrap uses a fractional (responsive) margin on the span9 left side.

I've patched our local copy of jscrollpane, but you may want a better fix.

Here is what I did.
1. Updated percentView calculation
   percentInViewH = Math.round((contentWidth / paneWidth)_100)/100;
   percentInViewV = Math.round((contentHeight / paneHeight)_100)/100;  
2. Updated hasContainingSpaceChanged block
                   if (hasContainingSpaceChanged) {
                       paneWidth = elem.innerWidth() + originalPaddingTotalWidth;
                       paneHeight = elem.innerHeight();
                       paneMarginWidth = Math.round((elem.outerWidth(true) - elem.width())_100)/100;
                       paneMarginFraction = (elem.outerWidth(true) - elem.width()) - parseInt(paneMarginWidth);
                       paneWidthMarginFraction = Math.round(paneMarginFraction_100)/100;
   
   ```
                   //Handles % margin calculation
                   paneWidth = paneWidth - paneMarginFraction;
   
                   container.css({
                       width: paneWidth + 'px',
                       height: paneHeight + 'px'
                   });
               }
   ```
3. Updated if pane=== undefined block
                   // TODO: Deal with where width/ height is 0 as it probably means the element is hidden and we should
                   // come back to it later and check once it is unhidden...
                   paneWidth = elem.innerWidth() + originalPaddingTotalWidth;
                   paneHeight = elem.innerHeight();
                   paneMarginWidth = Math.round((elem.outerWidth(true) - elem.width())_100)/100;
                   paneMarginFraction = (elem.outerWidth(true) - elem.width()) - parseInt(paneMarginWidth);
                   paneMarginFraction = Math.round(paneMarginFraction_100)/100;
   
   ```
               //Handles % margin calculation
               paneWidth = paneWidth - paneMarginFraction;
   ```

These changes resolved the issue. I'm sure there is a more elegant way, but this definitely resolved the issue.

**Comment by doclucas** [comment]
Your code is missing the multiplier sign `*` before each "100". Probably one of github's quirks...

**Comment by illuusio** [comment]
If this still issue please write a note
