### ISSUE TITLE
Scroll bars size not taken into account when computing percentInViewV and percentInViewH

### ISSUE THREAD

**Issue by antur123** [vitch/jScrollPane#210]
Values of `percentInViewV` and `percentInViewH` are calculated from content and panel initial dimensions.  When a scroll bar appears, as it is rendered inside the panel, there is less free space to show contents and scrolling can go wrong.

To fix this, an option is to re-calculate percent values after scroll bars have been created, so that they are positioned and dimensioned the right way.

So, after these lines are executed inside the `initialise()` function:

``` javascript
initialiseVerticalScroll();
initialiseHorizontalScroll();
```

This code can be added to fix that issue

``` javascript
if (isScrollableH) {
    // Horizontal scroll bar appears, so we must redimension vertically
    percentInViewV = (contentHeight + horizontalBar.outerHeight()) / paneHeight;

    // Check for vertical scroll, if there was none
    if (!isScrollableV) {
        isScrollableV = percentInViewV > 1;
        initialiseVerticalScroll();
    }
}
if (isScrollableV) {
    // Vertical scroll bar appears, so we must redimension horizontally
    percentInViewH = (contentWidth + verticalBar.outerWidth()) / paneWidth;

    // Check for horizontal scroll, if there was none
    if (!isScrollableH) {
        isScrollableH = percentInViewH > 1;
        initialiseHorizontalScroll();
    }
}
```

And that is it.  Please excuse me if I misunderstood something or if this issue is already reported and/or fixed.

Thanks!

**Comment by illuusio** [comment]
If this is still issue please reopen
