### ISSUE TITLE
Changing autoReinitialize setting doesn't work

### ISSUE THREAD

**Issue by lumpynifkin** [vitch/jScrollPane#219]
It seems if you try and change the autoReinitialize setting after already initializing to false, the change never get updated even if you call api.reinitialize({autoReinitialize:true}); 

This can be fixed by moving this code block

``` javascript
if (settings.autoReinitialise && !reinitialiseInterval) {
                    reinitialiseInterval = setInterval(
                        function()
                        {
                            initialise(settings);
                        },
                        settings.autoReinitialiseDelay
                    );
                } else if (!settings.autoReinitialise && reinitialiseInterval) {
                    clearInterval(reinitialiseInterval);
                }
```

above line 145 which returns if 

```
(!hasContainingSpaceChanged && previousContentWidth == contentWidth && pane.outerHeight() == contentHeight)
```

 this can be true if only the settings have changed and doesn't seem to be updated until manual reinitializations.  

I would like to know the best location to move this code block for efficiency purposes.

**Comment by illuusio** [comment]
If this is still issue please write a note
