### ISSUE TITLE
Content scrolls horizontally to where I click

### ISSUE THREAD

**Issue by andytorres** [vitch/jScrollPane#224]
I have a container with a div child containing a tree made with <a href="https://github.com/vakata/jstree">vakata/jstree</a>. The tree has a lot of nested `<ul>, <li> and <a>`  tags, with actions associated. The point is: When I click any of those a's, the cotent automatically scrolls **horizontally** to where I clicked.
Any particular reason for this, or maybe a way to fix it? Thanks in advance, 
Andy

**Comment by illuusio** [comment]
If this is still issue please write a note
