### ISSUE TITLE
issue with jscrollpane and reinitialise causing contentHeight to be incorrectly calculated

### ISSUE THREAD

**Issue by puzzledmonkey** [vitch/jScrollPane#225]
(using the latest zip download)

at line 165, contentHeight is calculated like so (and this is correct)

contentHeight = pane[0].scrollHeight;

however, at line 445, contentHeight is re-calculated like so :

contentHeight = pane.outerHeight();

this is incorrect, and means that scrollTo etc will usually fail. changing line 445 to

contentHeight = pane[0].scrollHeight;

fixes the issue.

sorry i am not sure how to attach a diff or anything, i've never used github before, but i hope this is simple enough so you can figure out what i'm talking about :)

cheers!

**Comment by illuusio** [comment]
Should be fixed on 2.2.0
