### ISSUE TITLE
If nothing changed since last check

### ISSUE THREAD

**Issue by Mojo1** [vitch/jScrollPane#229]
the If "nothing changed since last check is kind of buggy" -  dont't have time right now to point it out more exactly just commented it out for the moment. 
In any case I have a part in which i reinitialze the scrollbars on click. it happens that content width keeps equal on reinitializing. next click it changes. the plugin still thinks nothing changed and is like hung up wont react on anything.
some kind of logical issue

**Comment by illuusio** [comment]
Everything is broken. Always!
