### ISSUE TITLE
iPad - cannot separate fixed position scrollable "div" filter from 'main' scrollable content.

### ISSUE THREAD

**Issue by noeltd** [vitch/jScrollPane#232]
iPad - cannot separate fixed position scrollable "div" filter from 'main' scrollable content.

I have a webpage which contains 

1) A fixed position ( left-hand-side ) "filter" "div" contained within a scrollable "div" - hence use of jscrollpane.
2) 'main' content which also is scrollable 

The basic problem is that scroll only works on the "filter" div when the "main" content is at the top.  Other than that, attempts to scroll
on the "filter" is applied to the "main" content.

How can I separate the 2 so that the scroll for both the "filter" and "main" content act independently/separately?

See page 'http://www.atlantisstorm.com/test-scrolling.html' for demo of problem.

jscrollpane v2.0.14, mousewheel v3.1.3

Note this is only a problem iPad, seems to work fine in desktop browsers.

**Comment by illuusio** [comment]
If still issue reopen and write note.
