### ISSUE TITLE
Wrong height calculation inside of display:table-row

### ISSUE THREAD

**Issue by emirotin** [vitch/jScrollPane#233]
Here's my setup http://d.pr/i/TwRN

The wrapper block has display: table.
Two red blocks have display: table-row and height: 100px
Middle block (white) has display: table-row and height: auto
Inside of the middle block there's a div.scroll-pane with 

```
    height: 100%
    max-height: 100%
    overflow-y: scroll
```

When the page just loads (jScrollPane not added yet) it looks OK - the middle block takes all available space and the nested scroll-pane scrolls (natively).

Then JSP comes and sets jspContainer height to the whole wrapper's height (thus middle block expands too much http://d.pr/i/GCBG).

If then I go to Inspector and uncheck the height inline rule for the jspContainer it recalculates properly http://d.pr/i/4NNm.

**Comment by illuusio** [comment]
If you have this problem still then please contribute to newest generation of issue.
