### ISSUE TITLE
Uncaught TypeError cannot read 'msie' of undefined

### ISSUE THREAD

**Issue by mpmp0** [vitch/jScrollPane#243]
The dynamic height doc should be updated

http://jscrollpane.kelvinluck.com/dynamic_height.html
if ($.browser.msie) {}
I am using jquery 1.9.1

I believe that browser detection was removed with new jquery.
http://stackoverflow.com/questions/14793331/uncaught-typeerror-cannot-read-property-msie-of-undefined

**Comment by nkmdk-007** [comment]
So, the IE Cconditional comments have been removed in IE10 but you can
force IE10 to behave like IE9 using a clever little meta tag and therefore
Conditionals will work again :)

Certainly not ideal for a production site but could still work for your
example?...

On 30 July 2013 13:03, Kelvin Luck notifications@github.com wrote:

> Yeah - I noticed that when I was looking at the zepto site the other
> day...
> 
> In that case I think I'd be happy just getting rid of the msie conditional
> in this example - it's no bad thing throttling the events on all browsers
> (but in IE it caused a crash if I remember correctly)
> 
> Thanks for looking into it!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vitch/jScrollPane/issues/243#issuecomment-21786072
> .

##

**Comment by vitch** [comment]
I think I'd prefer just to loose the whole $.browser.msie conditional...
It's safe to throttle our resize handler in all browsers anyway...

**Comment by nmiddleweek** [comment]
Hi @vitch - Could you **please please** help me by removing the footer in your comment above that contains my name, email, mobile and blog link. I have pinged you an email and LinkedIn message with a bit more info. I will delete this comment once you've read it. Thank you so much!
