### ISSUE TITLE
Infinite width grow when autoreinitialise option and padding set

### ISSUE THREAD

**Issue by PaulAnnekov** [vitch/jScrollPane#245]
There is some strange bug occurs when **autoreinitialise** option is set to true and block has padding (but maybe table layout is the root of the problem).
Each time plugin re initializes its width grows. The more padding block has the faster it grows...

I have created simple example of such bug: http://jsfiddle.net/yz67W.
Try to remove padding and bug will not occur.

**Comment by PaulAnnekov** [comment]
@illuusio nice. Maybe some explanation why you closed it?

**Comment by illuusio** [comment]
Opps.. It was mistaken close as I haven't indicated anything here. Trying to sanitaze bugs out which doesn't have active person behind. I reopen this. Sorry!

**Comment by illuusio** [comment]
Any PR coming to this bug?

**Comment by illuusio** [comment]
This should be working now with latest commits if not please reopen.
