### ISSUE TITLE
Doesn't support HTML5 ability to have focus on any element due to tabindex

### ISSUE THREAD

**Issue by timspro** [vitch/jScrollPane#247]
HTML5 allows any element to have the tabindex set and thus any element can have focus. Right now, it appears jScrollPane is not correctly scrolling to a focused element that is not an input or a link.

I believe the problem is the following line:
900: pane.find(':input,a').unbind('focus.jsp').bind(
changing it to 
900: pane.find(':input,a,[tabindex]').unbind('focus.jsp').bind(
works for me, but this won't work for negative tabindex's.

**Comment by illuusio** [comment]
If this is still issue please add note
