### ISSUE TITLE
Hijack links doesn't work where there is more than on jScrollPane on the page

### ISSUE THREAD

**Issue by vitch** [vitch/jScrollPane#25]
As reported on the mailing list:
http://groups.google.com/group/jscrollpane/browse_thread/thread/9dff99a704bb5b49

See example showing the problem here:
http://www.jsfiddle.net/Ncv4R/10/

**Comment by illuusio** [comment]
Is this still issue?

**Comment by illuusio** [comment]
Duplicate with not so good explanation
