### ISSUE TITLE
Problem with putting inside the carousel (other script duplicates jScrollPane'd content)

### ISSUE THREAD

**Issue by m4gz** [vitch/jScrollPane#270]
I'v found a bug, with infinite carousel (like that http://tympanus.net/Development/CircularContentCarousel/ )  it is copying 1st element and attached to last, when clicking next button, and the scroll dont works in that 'new' elements of content, because they are copying as html, but not with attached events, and if i trying to add "$('.scroll-pane').jScrollPane();" after 'next' button event, its still not working. Is it possible to fix?

**Comment by illuusio** [comment]
Is this still problem?
