### ISSUE TITLE
jScrollPane not working properly within iframe on Safari 7

### ISSUE THREAD

**Issue by zagara** [vitch/jScrollPane#273]
Hi,
just wondering if anything could be done to fix a strange behavior of jScrollPane when applied to an iframe and viewed on Safari 7. When you first open the webpage, you can't scroll with the two-finger-gesture, only by dragging the scrollbar. When you reload the page, it works fine. Re-open the page after that (e.g. by clicking on a link), and again you can't two-finger-scroll. In any other browser I checked, everything seems to work fine. 
This behavior can also be reproduced by the example given on the jScrollPane webpage: http://jscrollpane.kelvinluck.com/iframe.html
Thanks!

**Comment by Almanah** [comment]
Hi,

This issue is [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=124139).
You can find some ways to fix it [HERE](http://stackoverflow.com/questions/24642157/workaround-for-iframe-mousewheel-bug-in-safari-6-1-7-0). I used "onmousewheel" attribute, it works fine.

**Comment by zagara** [comment]
Works like hell! Incredible. 
Good to know it's a bug and not me.
I didn't expect any response any more. Thank you so much!
