### ISSUE TITLE
Vertical bar geting cut of in chrome and safari

### ISSUE THREAD

**Issue by ajob3** [vitch/jScrollPane#282]
I have a website were in the vertical scroll bar is getting cut off. If you go to anther item in the menu item and come back all the elements are getting displayed. But when you refresh the page it the scroll bar gets shorter and some items are not displayed.

The web address is http://uk.palmers.com/news/

When you first visit the page and the click on the archives->2014->May the items on the bottom are getting cut off.

But then you go news->online Mentions-> Archives->2014->May then all the items are displayed.

But if you refresh the page some of the items on the bottom get cut off.

I have been trying to solve this by myself but cannot. I will really appreciate somebody to help my. I tanks in advance.

PS this issue is only in chrome and safari and not on explorer and Firefox.

**Comment by illuusio** [comment]
Is this still relevant?
