### ISSUE TITLE
AngularJs Node undefined

### ISSUE THREAD

**Issue by talymo** [vitch/jScrollPane#292]
When using jScrollPane with AngularJS, I have to set a timeout of 100 seconds on the jScrollPane initialization in order to avoid a TypeError in the console.

I don't know if this is a bug or not... Maybe just something you would want to share with your users who are using AngularJS.

**Comment by bodrovis** [comment]
That's strange, I was able to get it working like that in the directive:

```
  link: (scope, iElement, iAttrs) ->
    scrollpane = jQuery('#scrollbar1').jScrollPane({autoReinitialise: true, mouseWheelSpeed: 70})
```

**Comment by talymo** [comment]
Try to use one outside of a directive. Just use it inside of a controller.

**Comment by Amerr** [comment]
You can elaborate your situation that would really help in identifying the problem

**Comment by illuusio** [comment]
Is this still relevant?

**Comment by bodrovis** [comment]
Does not seem so. Angular has changed drastically and has no directives at all. But yeah, it *might* be relevant for people who are still on AngularJS...

**Comment by bodrovis** [comment]
Btw, it's really cool someone it maintaining this library again. I'll update the corresponding rubygem https://rubygems.org/gems/jscrollpane-rails asap :)

**Comment by illuusio** [comment]
Ok closing this and thanks for updating Ruby version!
