### ISSUE TITLE
scrollbar disappears in chrome when using jquery $()

### ISSUE THREAD

**Issue by aboutqx** [vitch/jScrollPane#294]
i have some images and do not set the height,and then the issue comes.Sometimes the scrollbar can't  display in chrome,but always works well in firefox.
Finally i change the $() to window.onload and fix it.I guess its a problem of caculating the height,chrome may not have the "place holder".
I think its not a bug but it should be mentioned.

**Comment by vitch** [comment]
This is covered in the [image demo](http://jscrollpane.kelvinluck.com/image.html) on the jScrollPane site...
