### ISSUE TITLE
False event 'jsp-arrow-change' after added content and autoreinitialisation

### ISSUE THREAD

**Issue by vaseninm** [vitch/jScrollPane#295]
When i`m added new content to pane block i catch event 'jsp-arrow-change' where isAtTop arguments is true, but position not is top. Why?
p.s. sorry for my bad english

**Comment by vitch** [comment]
Do you have an example URL? If you can put it up on [jsfiddle.net](http://jsfiddle.net) that makes it easier to help...

**Comment by vaseninm** [comment]
Yes. http://jsfiddle.net/Pchol/1arjuz45/2/

**Comment by illuusio** [comment]
Is this still relevant?
