### ISSUE TITLE
Support to verticalHeight

### ISSUE THREAD

**Issue by mauricio-frontend** [vitch/jScrollPane#305]
I notice that isn't  a attribute to personalize the height of the vertical bar, so I think that it's can solved add followed line in the plugin 

if (settings.verticalTrackHeight == 0) {
                        verticalTrackHeight = paneHeight;
                    } else {
                        verticalTrackHeight = settings.verticalTrackHeight;
                    }

**Comment by vitch** [comment]
What is your use-case?

Is it not served by using `caps`?

http://jscrollpane.kelvinluck.com/caps.html

**Comment by mauricio-frontend** [comment]
No... just add a option to custom the height, if the user want  a smaller scrollbar that the box.

**Comment by illuusio** [comment]
Is this still relevant if it is please make PR.
