### ISSUE TITLE
Scroll issue when textarea has greater height than scroll container

### ISSUE THREAD

**Issue by Ehcaon** [vitch/jScrollPane#307]
When you trigger the focus on a textarea with greater height than its scroll container, the vertical scroll position switch between the top and bottom position of the textarea.

Fiddle : http://jsfiddle.net/yz67W/3/
Click in and out of the textarea to see the issue.

Identical behavior with Chrome 43, IE11, Firefox 38.

Maybe the culprit is "function scrollToElement"
line "if (eleTop < viewportTop || stickToTop) { // element is above viewport"

Change to "if (eleTop <= viewportTop || stickToTop) { // element is above viewport"
No more back and forth between top and bottom on focus event.

**Comment by illuusio** [comment]
Is this still relevant?
