### ISSUE TITLE
Scrollbar not showing when used with flyPanels

### ISSUE THREAD

**Issue by georgeatgrayson** [vitch/jScrollPane#311]
Under normal circumstances, I have encountered few problems with jScrollPane. However, when used with flyPanels - https://github.com/SubZane/flyPanels - with the 'scroll-pane' class on the div surrounding the nav; the scrollbar is not shown, and upon looking at the F12 code, the entire div containing the scrollbar is not added to the code at all.

**Comment by illuusio** [comment]
Is this still relevant?

**Comment by illuusio** [comment]
If this is still issue please notice
