### ISSUE TITLE
small size scroll bar aligned in middle

### ISSUE THREAD

**Issue by Purush0th** [vitch/jScrollPane#315]
Hi all,

I would like to have small horizontal scrollbar that align in the middle. currently by default the scroll bar spans to the entire scroll pane container. Is there any option to do that? 
Here is the image that illustrates the result I have needed.
![image](https://cloud.githubusercontent.com/assets/1386902/9113338/ae77d47a-3c71-11e5-8758-218b276851d1.png)

Here is the fiddle for the problem
http://jsfiddle.net/Purushoth/f68rzs75/

**Comment by vitch** [comment]
Do [caps](http://jscrollpane.kelvinluck.com/caps.html) solve your problem?

**Comment by Purush0th** [comment]
Caps works fine for me. Thanks @vitch
