### ISSUE TITLE
Problem with scroll content in iframe ipad

### ISSUE THREAD

**Issue by Tommy10802** [vitch/jScrollPane#317]
Hello, thanks for nice and great plugin.
I have a problem with scrolling content at iframe on ipad.
I already did a research and i found, that panel and content width didnt calculate correctly, but only on ipad.
So the horizontal scrollbar didnt show up.
I tried your example iframe page (http://jscrollpane.kelvinluck.com/iframe.html) on ipad and didnt work horizontal scroll bar correctly too.
Thanks for any advice or help

**Comment by illuusio** [comment]
Is this still relevant?
