### ISSUE TITLE
not ignoring visibility: hidden elements

### ISSUE THREAD

**Issue by okliv** [vitch/jScrollPane#318]
i have div with `visibility: hidden` css attribute but jscrollpane interprets it like it is visible - just makes scroll much bigger

`display: none` not really helps too but if i remove hidden html - scroll's height becomes correct

**Comment by vitch** [comment]
Can you provide a [jsfiddle](http://jsfiddle.net/)?

**Comment by jayharland** [comment]
Isn't that the behavior difference between visibility: hidden and display: none though?

`visibility: hidden` hides the element but keeps keeps it in the document flow
`display: none` takes the element out of the document flow
