### ISSUE TITLE
Scroll not working for touch pad

### ISSUE THREAD

**Issue by gamevnlc** [vitch/jScrollPane#321]
Hello. I am using the jscrollPane plugin. I create the scroll bar for ajax content . Everything is ok, The scroll bar is working correct on Window OS. But It isn't work in chrome browser on MacOS. When I try two finger scroll at touch pad, the scroll bar not working. I can only scroll the page , not the div has the jscrollpane. When I try to disable the scroll bar of page by set the overflow to hidden. And try again in the div has jscrollpane. It's will automatically scroll to top or bottom. I don't know why. Please help me. Thank you

**Comment by illuusio** [comment]
Is this still relevant?

**Comment by illuusio** [comment]
Should work.
