### ISSUE TITLE
Issue with elements who's height is decided by a ratio of it's width.

### ISSUE THREAD

**Issue by CaelanStewart** [vitch/jScrollPane#329]
Hi,

I encountered an issue that comes up when there is an element inside the jScrollPane content who's height is a ratio of the width and the width is a percentage of the parent's width. The reason is when jScrollPane initialises, the width of the `.jspPane` is temporarily changed (on line 180) before the `scrollHeight` is retrieved (on line 192). So when `percentInViewV` is set, the `paneHeight` is not correct.

I would fix it myself, but I don't have time to test what unintended implications doing that might have, I'm reporting this from work now. So in the mean time, since it worked in my case, I just forced `width: 100%` in the .jspPane element, since I don't need horizontal scrolling.

**Comment by illuusio** [comment]
Is this still relevant?

**Comment by illuusio** [comment]
This should be resolved now with new resize code if not please reopen and submit PR
