### ISSUE TITLE
api.reinitialise() does not urge to display scrollbar when element not visible

### ISSUE THREAD

**Issue by lexected** [vitch/jScrollPane#340]
Let's say you have

```
<div style="display: none" id="parent">
    <div class=".scroll-pane" id="child"></div>
</div>
```
1. Load contents into the `#child` and perform `api.initialise()`
2. Set `#parent`'s `display` to something different than `none` to make it visible
3. The scroll bar will not show and the data overflow of `#child` will remain hidden.

I would not say this is generally desired, since you often want to load data into `div`s before they're made visible, and `display: none` is the preferred version of hiding things by jQuery effects.

Not tested with `visibility: hidden`.

**Comment by vitch** [comment]
jScrollPane can only calculate heights when content is visible. [auto_reinitialise](http://jscrollpane.kelvinluck.com/auto_reinitialise.html) could maybe help you or you could show the content, initialise the scrollpane and hide the content.

Unfortunately I don't have time to support jScrollPane these days so it is unlikely I'll make any changes - if you want to submit a PR which automatically shows, calculates and hides the scrollpane if it's hidden then I'd be happy to merge it...

**Comment by lexected** [comment]
I'll dive into it tonight! :) ... hope I'll be successful....

**Comment by illuusio** [comment]
Is this still issue?
