### ISSUE TITLE
Destroyed sidelayout and no scrollbar

### ISSUE THREAD

**Issue by V10lator** [vitch/jScrollPane#342]
I fiddled with this for hours now but no matter what I try: It's always the same. To make this even more worse even solutions found on stackoverflow won't work (even "working examples" on stackoverflow are broken).

Default browser scrollbar: 
![Image](https://picload.org/thumbnail/rddgiraw/site-good.jpg)
https://picload.org/image/rddgiraw/site-good.png

Same site with jScrollPane:
![Image](https://picload.org/thumbnail/rddgirai/site-bad.jpg)
https://picload.org/image/rddgirai/site-bad.png

**Comment by illuusio** [comment]
Is this still issue?
