### ISSUE TITLE
Width of container with inline items.

### ISSUE THREAD

**Issue by dbauszus-glx** [vitch/jScrollPane#343]
I love the jscrollpad plugin. Yet there is one thing I just can't get my head around. I sometimes want to display several items on a line. I am doing so by having all items as inline-block and then add a spacer block item when i want to start the next line. When I decrease now the window height so that the scrollbar kicks in, the last item in the line gets pushed into the next line. Another problem is that the the container always stays at it's fixed width. If I toggle to hide the additional buttons on a line the width of the container stays the same.

I made a jsfiddle to show the problem.
http://jsfiddle.net/goldrydigital/zez3gz21/

The scroll menu loads like this.
![image](https://cloud.githubusercontent.com/assets/22201617/19247045/2de31d98-8f21-11e6-9bc1-4870d101e45c.png)

When I reduce the window height the scrollbar is shown and the last item is pushed into the next line.

![image](https://cloud.githubusercontent.com/assets/22201617/19247078/5e12b7da-8f21-11e6-841a-1a939d9d06b1.png)

I toggle the additional line item to be hidden (clicking on the first button in line), but the container stays the same width. :(

![image](https://cloud.githubusercontent.com/assets/22201617/19247169/bfd1977a-8f21-11e6-8d20-73a1fbdefedc.png)

Would be awesome if somebody can help me here.

**Comment by GEOLYTIX** [comment]
If I run the fiddle with the button group set to display:none the container cuts of the buttons and I will not grow when the hidden buttons are triggered to be shown. The buttons are then all pushed down.#

![image](https://cloud.githubusercontent.com/assets/22201617/19247475/576ca68c-8f23-11e6-96d4-0c0ac5f51193.png)

**Comment by GEOLYTIX** [comment]
Just realised that there hasn't been much activity on this repo for a little while. I updated the jsFiddle with a hacky fix.

I need to hide the display:none; elements again after I initialise the jScrollPane and force the width.

I then force the width after toggling the display. A short timeout on the display makes sure the items are only displayed after the container width has been adjusted.

```
$('.ctrl__left').jScrollPane({
  autoReinitialise: true
});
$('.btnGrp__transportlayers').hide();
$('.jspContainer').width(80);

$('#btnTransport').on('click', function() {
  if ($('#btnTransport').hasClass('mdl-button--active')) {
    $('#btnTransport').removeClass('mdl-button--active');
    $('.btnGrp__transportlayers').hide();
    $('.jspContainer').width(80);
  } else {
    $('#btnTransport').addClass('mdl-button--active');
    $('.jspContainer').width(290);
    setTimeout(function(){ $('.btnGrp__transportlayers').show(); }, 100);
  }
});
```

**Comment by vitch** [comment]
Sorry for the slow reply - as you noticed I haven't had time to work on jScrollPane in a long while.

I'm not sure what is going wrong in your case but it sounds like you have a workaround which is great!

Looking at the code above, the problem may be because you are setting the width of the `jScrollPaneContainer`. IIRC you should never mess with the size of this as jScrollPane manages it itself. You can set the width of a containing element if you want to...

Hope it helps!

**Comment by illuusio** [comment]
Couple years has passes but is this still relevant?

**Comment by dbauszus-glx** [comment]
It's not for my concern. I ended up writing my own snippet for a scroll pane implementation a few months ago to work with vanilla js as I banished all jquery from my projects.
