### ISSUE TITLE
Mousescrolling stops working when scrolling over embedded iframe

### ISSUE THREAD

**Issue by ageurts** [vitch/jScrollPane#347]
I don't know if this issue was reported before, but I can't seem to find it anywhere else.

When embedding certain iframes (for example facebook and instagram) in the scrollable content, mousescrolling stops when the mouse is over the iframe. You can get past the iframe by dragging the scrollbar or if you have padding/margins on the iframe by scrolling left or right of the iframe, but otherwise you're stuck.

I made a fiddle borrowing on some other code to illustrate the issue: http://jsfiddle.net/nfpt8tp3/2/

Is there any way around this?

**Comment by vitch** [comment]
I'm afraid that there is no way around this. The mouse events don't bubble from the iframe.

Additionally, I don't support this plugin any more. It hasn't been updated in a long time and I don't have any use for it any more. Sorry!
