### ISSUE TITLE
Scroll bar does not appear to support RTL languages

### ISSUE THREAD

**Issue by kercheval** [vitch/jScrollPane#35]
When using the plugin in RTL contexts (Arabic and Hebrew are examples), the following problems occur.
- The vertical scroll bar does not correctly switch to the opposite side of the scrolling area
- The horizontal scroll bar does not correctly align to the opposite side of the scrolling area
- The horizontal scroll bar incorrectly sets the initial scrolling region to the wrong side of the scrolling area

The positioning of the vertical and horizontal scroll bar can be corrected via CSS, but the initial scroll location must be solved in another way (and built support for RTL language would be preferable.

**Comment by ahmadalfy** [comment]
This might be too late but the first point cannot be addressed with CSS. The position is calculated by subtracting the `left` value using JavaScript. All what's needed is just to reverse it. I will see what I can do on the plugin and update you

**Comment by illuusio** [comment]
Are @ahmadalfy  still workin on this?

**Comment by ahmadalfy** [comment]
@illuusio I didn't honestly check it. Keep it closed and I will update the thread and ask you to reopen it if I made progress. Probably will check it by the end of today or tomorrow.
