### ISSUE TITLE
main prop removed from package.json -> Build failed

### ISSUE THREAD

**Issue by JavRok** [vitch/jScrollPane#350]
Hi, suddenly our build in our CI server is broken. This happened after jscrollpane got updated to latest version (2.1.1). We just required the module with `require('jscrollpane')` and Webpack did the work to find it in node_modules. I noticed that the 'main' property was removed from package.json, that probably was what webpack used to guess what file to include. 

Is there a reason for this change?

**Comment by vitch** [comment]
@illuusio has been looking after this plugin recently and can hopefully help out.

In the meantime, you might want to lock down your dependency on `jscrollpane` to `2.0.23` (without any `^` or `~`) in your `package.json`...

**Comment by illuusio** [comment]
Ok I assumed something get borked when I update NPM. I'll re-add main

**Comment by illuusio** [comment]
There is now release candidate 2.1.2-rc.1 which should work as before on NPM

**Comment by JavRok** [comment]
Thanks for the quick reaction !

**Comment by illuusio** [comment]
DId it solve problem? If it did please close issue

**Comment by JavRok** [comment]
Sorry I'm unable to install the latest, I get this:

`+--  jscrollpane@2.1.2-rc.2  invalid
| `-- jquery@3.2.1
`-- UNMET PEER DEPENDENCY sinon@*`

Do you know why is this happening?

**Comment by illuusio** [comment]
Main problem seems to be that NPM has changed the way they treat peer depencies. More info: https://stackoverflow.com/questions/35738346/how-to-solve-npm-unmet-peer-dependency

**Comment by illuusio** [comment]
Can this be closed?

**Comment by JavRok** [comment]
Hi, I just confirmed that issue is fixed on version 2.1.2-rc.2.

Thanks!
