### ISSUE TITLE
Line with console.log

### ISSUE THREAD

**Issue by memento86** [vitch/jScrollPane#352]
Hello,

In the line 165 of jquery.jscrollpane.js there is the next code: console.log('newPaneHeight = ' + newPaneHeight);

The same happens in jquery.jscrollpane.min.js

Besides, if you open the browser console, there is an infinite loop running console.log.

**Comment by illuusio** [comment]
Ok thanks for report. I'll remove that. How didn't I hit that one?

**Comment by memento86** [comment]
I'm using the plugin with this configuration:

    $(this).jScrollPane({
         autoReinitialise: true,
         autoReinitialiseDelay: 100
    });

**Comment by illuusio** [comment]
This should be fixed now please test with latest Git

**Comment by memento86** [comment]
Hi! The problem continues.

**Comment by illuusio** [comment]
So how do I test it?

**Comment by memento86** [comment]
Why this code runs infinitely?

**Comment by illuusio** [comment]
Current implementation for resize is like it polls in intervals with 'autoReinitialiseDelay: 100' 100 ms in you case. It reinitialized itself so as you said it runs infinitely. If you have time and motivation there is pull request vitch/jScrollPane#341 which will change things to event based.
If time and motivation is not you thing  and if you don't need autoresize then don't use autoReinitialise. I try to merge that pull request in some point of time near future but as I don't need it by myself it's not top of the list.

**Comment by memento86** [comment]
Ok. Thank you for your explanation :)

**Comment by illuusio** [comment]
It's removed in new release
