### ISSUE TITLE
NPM shows rc releases tagged as "latest"

### ISSUE THREAD

**Issue by ZachTRice** [vitch/jScrollPane#358]
When you publish a pre-release package to npm (packages tagged with `-rc.x` or any other `-alpha` / `-beta` tag) you should publish to npm using `npm publish --tag next`. This will prevent users from accidentally pulling in the `-rc.1` packages when pointed to the latest release. The default tag npm uses is "latest" if you don't specify this parameter when publishing. 

You can see this now in the npm tag tab: https://www.npmjs.com/package/jscrollpane
Here is an example of using the next tag: https://www.npmjs.com/package/worldview-components

It looks like you have the github pre-release / release process down and are using the correct tags, just need to tweak your npm publish step.

**Comment by ZachTRice** [comment]
Also, "next" could be named anything; "next" is a standard tag name, but it could be anything you want to denote the next or pre-release package version.

**Comment by illuusio** [comment]
Thanks for the tip! I'll try to follow this one on next release cycle.
