### ISSUE TITLE
Console error in jquery when use cursor keys

### ISSUE THREAD

**Issue by RWAP** [vitch/jScrollPane#367]
If you move the down cursor below the last autocomplete suggestion, jquery reports an error "unknown item"

It might be the set up I am using, but appears to affect this module - jquery ui-autocomplete is fine and returns your cursor to the input field.

**Comment by illuusio** [comment]
Is this JScrollPane problem?

**Comment by RWAP** [comment]
I believe it is jScrollPane - I switched to jquery ui-autocomplete in the end and it worked fine.

I can't provide a link to a test page (and the demo page for jScrollPane is not working) - however, it was being invoked by the following:

```
<script type="text/javascript">
			var suggestions = ["buying", "pr", "pre-loved", "product", "product code", "product codes", "product description", "red", "sell an item"];
		var settings = {
			showArrows: false
		};

		var _jScrollPane, _jScrollPaneAPI,
	   		_jSheight = 100;
		$(document).ready(function() {
			autocomplete = $('#helpKeyword').autocomplete({
				minLength: 1,
				source : function(request, response) {
					myResponse = new Array();
					myRequest = request.term.toLowerCase();
					for (var j in suggestions) {
						if (suggestions[j].toLowerCase().startsWith(myRequest)) {
							myResponse.push(suggestions[j]);
						}
					}
					response(myResponse);
				},
				open: function() {
					$('.ui-autocomplete').width($(this).width());
					if (undefined !== _jScrollPane) {
						_jScrollPaneAPI.destroy();
					}
                    $('.ui-autocomplete').removeClass('mobile-dropdown-autocomplete').css({'overflow-y':'hidden','height':_jSheight});
                    $('.ui-autocomplete > li')
                        .wrapAll($('<div class="scroll-panel"></div>')
                        .width($(this).width())
                        .height(_jSheight));
                    _jScrollPane = $('.scroll-panel').jScrollPane(settings),
                    _jScrollPaneAPI = _jScrollPane.data('jsp');
				},
				close: function(event, ui) {
                    _jScrollPaneAPI.destroy();
                    _jScrollPane = undefined;
				},
				select: function(event, ui) {
					$(this).val(ui.item.label);
					return false;
				}
			});
		});
    </script>
```

**Comment by RWAP** [comment]
A little more testing and it seems to be the interaction with the custom scroll bar we are using - jScrollPane does not appear to show a scroll bar at all - maybe that is causing the issue?

**Comment by illuusio** [comment]
jScrollPane doesn't show scrollbar if size fits in screen if not forced

**Comment by RWAP** [comment]
So how do you force the scrollbar - the aim is to reduce the height of the panel to show force it (ie show max of 3 options in the jScrollPane drop-down)...

**Comment by illuusio** [comment]
As seems docs website is down. Options can be found as html at 'examples/settings.html' directory.

**Comment by vitch** [comment]
I've just fixed the docs site - it was broken by changes someone else had done to the contents of this repository...

**Comment by RWAP** [comment]
Many thanks - that makes it easier.  I will close this issue now as it was not the fault of jScrollPane
