### ISSUE TITLE
dynamic width not working with display: table elements

### ISSUE THREAD

**Issue by MilosRasic** [vitch/jScrollPane#37]
Tried to use jScrollPane with a div contained in a parent whose width changes dynamically. Used the workaround listed in the known issues by setting the div's width to 100% in css. This made everything work except that the jScrollPane div would not shrink when its partent's width was decreased. We accidentally discovered that this was due to that fact that one of jScrollPane div's parents, a certain div between the jScrollPane div and the one that was resized, had display: table set in css. Everything worked fine after removing display: table from this div.

**Comment by illuusio** [comment]
This should be work now with new resize code.
