### ISSUE TITLE
Jquery 3.5.0 Security Fix Closing HTML Tags

### ISSUE THREAD

**Issue by melloware** [vitch/jScrollPane#376]
See: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

You can't do this anymore...
```javascript
$('<div class="jspVerticalBar" />')
```

You have to add the closing tags yourself like
```javascript
$('<div class="jspVerticalBar"></div>')
```

**Comment by illuusio** [comment]
Can you make PR?

**Comment by illuusio** [comment]
This should be fixed in master now

**Comment by melloware** [comment]
Nice work! Looks good to me.

**Comment by illuusio** [comment]
This can be closed then?
