### ISSUE TITLE
Jquery 4.0: Use of number-typed values is deprecated

### ISSUE THREAD

**Issue by melloware** [vitch/jScrollPane#377]
See: https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-use-of-number-typed-values-is-deprecated-in-jqueryfncss

**JQMIGRATE: Use of number-typed values is deprecated in jQuery.fn.css**
Cause: In past versions, when a number-typed value was passed to .css() jQuery converted it to a string and added "px" to the end. As the CSS standard has evolved, an increasingly large set of CSS properties now accept values that are unitless numbers, where this behavior is incorrect. It has become impractical to manage these exceptions in the jQuery.cssNumber object. In addition, some CSS properties like line-height can accept both a bare number 2 or a pixel value 2px. jQuery cannot know the correct way to interpret `$.css("line-height", 2)` and currently treats it as "2px".

Solution: Always pass string values to .css(), and explicitly add units where required. For example, use `$.css("line-height", "2")` to specify 200% of the current line height or `$.css("line-height", "2px")` to specify pixels. When the numeric value is in a variable, ensure the value is converted to string, e.g. `$.css("line-height", String(height))` and `$.css("line-height", height+"px")`.

**Comment by illuusio** [comment]
This should be fixed in master now

**Comment by melloware** [comment]
I did add one comment where I thought you might be missing `+ 'px'`

**Comment by illuusio** [comment]
Ok now it should be added.. please test that nothing is broke on your side and then I release

**Comment by melloware** [comment]
So far testing in my use cases everything is working so it looks good to me.  I think its safe to release.
