### ISSUE TITLE
Still "border-box" problem

### ISSUE THREAD

**Issue by cmpt1** [vitch/jScrollPane#382]
There is a still problem when using "border-box" (jScrollPane - v2.2.3-rc.1 - 2020-06-26)

	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;	
	
![border-box](https://user-images.githubusercontent.com/44491684/110634176-17a18800-81c3-11eb-8165-0e8e552d62a1.png)

**Comment by illuusio** [comment]
Ok this is fixed?

**Comment by cmpt1** [comment]
Yes fixed
