### ISSUE TITLE
Cannot detect contentHeight

### ISSUE THREAD

**Issue by TwistedLogic** [vitch/jScrollPane#41]
When I run jScrollPane on a hidden panel, contentHeight is always detected as 0px, and it doesn't let scrollbar to appear.

I wonder why the "width trick" wasn't used for height too during initialization. In fact commenting:
  //contentHeight = pane.outerHeight();

and inserting:
contentHeight = Math.max(pane.outerHeight(), clonedElem.outerHeight());

right before the temporary wrapper deletion:
tempWrapper.remove();

makes all my stuff working as well.

**Comment by illuusio** [comment]
If this is still issue with 2.2.0 please reopen
