### ISSUE TITLE
Drag not stopping

### ISSUE THREAD

**Issue by judahtanthony** [vitch/jScrollPane#44]
This may just be me, but when I mouse down on the drag-handle, start dragging, then mouse up NOT over the drag-handle, the dragging action never stops.

I haven't looked at the code, but it is as if the drag start is on the drag handle's mouse down, and the drag stop is on the drag handle's mouse up.  But instead the drag stop should be on the window's mouse up, so that you can mouse up anywhere and stop the drag animation.

Using jScrollPane - v2.0.0beta5 - 2010-10-18

**Comment by illuusio** [comment]
If this is still issue please reopen.
