### ISSUE TITLE
Reinitialising causes extra growth issues when the target element has padding.

### ISSUE THREAD

**Issue by DragonDTG** [vitch/jScrollPane#51]
When reinitialising the scroll pane, you perform a statement to see if the containing space has changed with this line:

```
hasContainingSpaceChanged = elem.innerWidth() + originalPaddingTotalWidth != paneWidth || elem.outerHeight() != paneHeight;
```

However, during initialization, the element's padding has been consumed into the element's innerWidth, moved to the jspPane, and the element's padding is set to 0. Therefore, I believe this line and the subsequent line should be changed to (With the assumption that no other external forces re-added the padding back into the element):

```
hasContainingSpaceChanged = elem.innerWidth() != paneWidth || elem.outerHeight() != paneHeight;

if (hasContainingSpaceChanged) {
    // paneWidth = elem.innerWidth() + originalPaddingTotalWidth;
    // Change to
    paneWidth = elem.innerWidth();
    paneHeight = elem.innerHeight();
    container.css({
        width: paneWidth + 'px',
        height: paneHeight + 'px'
    });
}
```

On the note of padding consumption, when destroying the scroll pane, we should re-add the padding back in and re-size the original element as well as removing the 'jsp' from the data. Therefore I propose adding these line to the destroy method.

```
elem.css('padding', originalPadding);
elem.width(paneWidth - originalPaddingTotalWidth);
elem.data('jsp', null);
```

I was creating a ui combobox that uses your scrollbar instead of the native one. However when the results returned something that didn't need scrolling, I would just destroy the scrollbar if there was one. The padding is used to allow the browser 
to render a border radius-correctly.

BTW, this is a wonder plugin, thanks!!!

**Comment by illuusio** [comment]
If this is still issue please write note and i'll reopen
