### ISSUE TITLE
Content hidden if scrolled down when reinitialising and content height no longer requires scrollbars

### ISSUE THREAD

**Issue by EdRyan** [vitch/jScrollPane#54]
I am using jScrollpane to wrap a jsTree element, and I have it set to reinitialize the jScrollpane every time a tree node is expanded or collapsed.

I have noticed that if you expand nodes so that a scrollbar is needed, then scroll down in the jScrollpane, and collapse a few nodes so that a scrollbar is no longer needed, the scrollbars disappear but the top position of the scrollpane is not reset to zero, cutting off any content above the initial scroll point.

I was able to correct this specific issue in my case by making the following code addition to the initialise() function in the else block around line 186 (v2.0.0b10 2011-02-04*):

```
if (isMaintainingPositon) {
    lastContentX = contentPositionX();
    lastContentY = contentPositionY();
    if (!isScrollableV) pane.css("top",0); // Added
}
```

It would be helpful if someone more familiar with the project could review this and see if that is the best way to resolve the issue and commit it.  It also does not resolve the same issue with the horizontal scrollbar.

**Comment by illuusio** [comment]
This should be resolved
