### ISSUE TITLE
reinitialise does not work, if only the contentWidth changes

### ISSUE THREAD

**Issue by aFarkas** [vitch/jScrollPane#63]
The contentWidth is not computed in initialise, so the following check is true, if only the contentWidth but not the contentHeight changes (i.e.: previousContentWidth == contentWidth is always/mostly true) :

```
    if (!hasContainingSpaceChanged && previousContentWidth == contentWidth && pane.outerHeight() == contentHeight) {
        elem.width(paneWidth);
        return;
    }
```

**Comment by illuusio** [comment]
If this is still issue please contribute to newest Issue.
