### ISSUE TITLE
Cannot scroll to bottom in FireFox 4 when using @font-face

### ISSUE THREAD

**Issue by pbz** [vitch/jScrollPane#76]
Cannot scroll to bottom in FireFox 4 when using @font-face, ie some text at the bottom remains hidden and can never be seen, ie jspPane height is calculated incorrectly because the line-height is calculated before the font is loaded.

What steps will reproduce the problem?
1. If the font family specified for some text in the scrollable references an @font-face declaration specify a src font file

With some fonts the results would probably be the opposite, ie over scrolling. This appears to be related to line-height. It seems FF displays the text first with a fallback font, and if the line-height of this font varys from the final font used to display then the height of jspPane is not calculated correctly. A work around is to explicitly specify the line-height in css. autoReinitialise might also work around this issues, but for me turning this on was causing my div to grow in width infintely.

What version of the jScrollPane are you using? v2.0.0beta11 
On what browser? FF 4.0.1
And operating system? Windows XP SP3

Please provide a URL to a page displaying the problem.
http://reflectivitydesign.com/jscrollpanebug.php

Please provide any additional information below.

**Comment by illuusio** [comment]
Is this still issue. If it is then please reopen.
