### ISSUE TITLE
contentHeight not calculated correctly in ie7

### ISSUE THREAD

**Issue by dschenk** [vitch/jScrollPane#90]
Version: 2.0.0beta10
Line: 163

`contentHeight = pane[0].scrollHeight;`

contentHeight gets calculated too small in IE7 when having less than 22 elements. This probably depends on styling too, but when there were more elements, the height is correct, when there are less, no verticalScrollBar gets displayed.

If the line gets changed to: 

`contentHeight = jQuery(pane[0]).height();`

It works.

**Comment by illuusio** [comment]
Hopefully there ain't people who use IE7 anymore. If there is please post note and reopen.
