### ISSUE TITLE
hidden content

### ISSUE THREAD

**Issue by laboratorio72** [vitch/jScrollPane#95]
Hi Kevin!

This is a minor thing. But the vertical bar hiddens some parts of the "#scroll" content. 

Here an snapshot of what happens:

http://imageshack.us/photo/my-images/97/jscrollpane.png/

The only solution that I get is to put another div inside my "#scroll". With the same width - the vertical width..

Just in case, reported. 

Thanks

Mateus

**Comment by illuusio** [comment]
If this is still issue please reopen and post note.
