### ISSUE TITLE
issue with vertical scrollbar height

### ISSUE THREAD

**Issue by NicoB1981** [vitch/jScrollPane#98]
First, jscrollpane is great good work!

Secondly, I just had an issue, with the scroll pane not initialising correctly. The element was hidden at time of initialisation, so that I when it was shown called reinitialise again - as I have done on many other elements before. This time it didn't work.

I traced through the code (Version 2.0.0beta10 - (2011-04-17)) and found the problematic line:

In line 425 in resizeScrollbars()     "contentHeight = pane.outerHeight();" this line returns 0 - so that the corresponding height calculations afterwards divide by 0 and get infinity - and a very large drag bar. I am not sure why you use pane.outerHeight here, because in a couple of lines above you used pane[0].scrollHeight instead - which does seem to give the correct height.

So to fix the issue I added the following lines below. I use the conditional because I'm not familiar with the reasons why your choise goes to pane.outerHeight(). I suppose at other times this might deliver a better value whereas scrollHeight might be erronous. So these lines only step in, in case outerHeight fails.

if (contentHeight == 0) {
         contentHeight = pane[0].scrollHeight;
}

Just thought to let you know

Anyway, thanks for your good work!

Nico

**Comment by illuusio** [comment]
If this is still issue please reopen
